var d = new Date();
var daylist = new Array("Sun.", "Mon.", "Tues.", "Wed.", "Thurs.", "Fri.", "Sat.");
var weekday = daylist[d.getDay()];
var day = d.getDate();
var monthlist = new Array("Jan.", "Feb.", "Mar.", "Apr.", "May", "June", "July", "Aug.", "Sep.", "Oct.", "Nov.", "Dec.");
var monthname = monthlist[d.getMonth()];
var year = d.getFullYear();
var fulldate = weekday + ", " + day + " " + monthname + " " + year;
document.getElementById("datestring").innerHTML = fulldate;
